### ISSUE TITLE
Use Git's branching and merging features for better productivity

### ISSUE THREAD

**Issue by docprofsky** [Coconuts2486-FRC/FRC2018#1]
Git makes branching and merging easy. This is to enable concurrent work on different parts of a piece of software by different people at the same time. The advantage of branching is that it allows changes to be made without worrying about other changes or needing to be perfect before sharing it. Branches also allow the use of pull requests, in which changes can be reviewed before incorporating them into the main code.

**Comment by zachies** [comment]
No.

**Comment by TaeSeanDo** [comment]
Umm... I'm pretty sure that "No" is spelled "Nougheux" as derived from its proper French etymology.  Not to split haires bute Iye thinke youe shoulde checke yaure faxs.

**Comment by zachies** [comment]
mAh.
